pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "ReverieVR"
include(":app")
include(":controller-app")
include(":cardboard")
project(":cardboard").projectDir = file("third_party/cardboard/sdk")
